[package]
name = "egltest"
version = "0.1.0"
authors = ["darkstalker <slayerbeast@gmail.com>"]

[dependencies]
x11 = { version = "2.9.0", features = ["xlib"] }  # this triggers the bug
custom_egl = { path = "custom_egl" }
custom_gl = { path = "custom_gl" }
